### PR TITLE
Add new caveat

### PR DESCRIPTION
**Pull request by slang25**
Please close if I am incorrect. This library requires that this sync context is flowed through the code.

### CODE REVIEW

**Comment by benaadams** [comment]
This is correct

**Comment by slang25** [comment]
It's not that it won't work inside the awaited method, it's that calls below within the same async method will run with a null context.

**Comment by slang25** [comment]
Let me create a sample to be clear

**Comment by slang25** [comment]
@benaadams See here:
https://github.com/slang25/Ben.BlockingDetector/blob/await-example/src/Ben.BlockingDetector.Sample/Controllers/HomeController.cs#L24
When you remove the first `await`, the detection works.

**Comment by benaadams** [comment]
Should now even catch moving off the sync context for Tasks; though it won't catch `Monitor.Wait` etc if you do; so not removing the caveat just yet

**Comment by slang25** [comment]
https://github.com/benaadams/Ben.BlockingDetector/commit/d651e390011eeecbd4328b6cdc4d0bb365d44c0e#r26963867
I'm enjoying "Tips of the Toub"

**Comment by benaadams** [comment]
> I'm enjoying "Tips of the Toub"

@stephentoub's the bringer of magic

**Pull request merged**
